// Rebuild the local-file fallback after editing questions.json.
const fs = require('node:fs');
const path = require('node:path');
const bank = JSON.parse(fs.readFileSync(path.join(__dirname, 'questions.json'), 'utf8'));
if (!Array.isArray(bank.questions)) throw new Error('questions must be an array');
const ids = new Set();
for (const q of bank.questions) {
  if (typeof q.id !== 'string' || ids.has(q.id)) throw new Error('Question IDs must be unique strings');
  if (!Array.isArray(q.choices) || q.choices.length < 2 || !Number.isInteger(q.answerIndex) || q.answerIndex < 0 || q.answerIndex >= q.choices.length) throw new Error(`Invalid answers in ${q.id}`);
  if (!q.source?.file || !Array.isArray(q.source.pages) || !q.source.pages.length) throw new Error(`Missing source in ${q.id}`);
  ids.add(q.id);
}
fs.writeFileSync(path.join(__dirname, 'questions-data.js'), '// Generated from questions.json. Do not edit this file.\nwindow.QUIZY_DATA = ' + JSON.stringify(bank, null, 2) + ';\n');
console.log(`Bundled ${bank.questions.length} questions.`);
