// Generated from questions.json. Do not edit this file.
window.QUIZY_DATA = {
  "version": 1,
  "course": "COMS4060A - Data Visualisation and Exploration",
  "scope": "2026-09-30 quiz; lectures 1–6",
  "questions": [
    {
      "id": "L1-001",
      "lecture": 1,
      "concept": "Why explore data",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          9,
          10
        ]
      },
      "question": "What is the main purpose of exploring data before applying a machine-learning method?",
      "choices": [
        "To understand its patterns and problems before choosing an approach",
        "To guarantee that the chosen model will be accurate",
        "To remove all unusual observations automatically",
        "To replace the need for testing the model"
      ],
      "answerIndex": 0,
      "explanation": "The lecture frames exploration as making sense of data first. It informs later choices but does not guarantee accuracy."
    },
    {
      "id": "L1-002",
      "lecture": 1,
      "concept": "Why explore data",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          11
        ]
      },
      "question": "A feature has a much larger numerical spread than other features and dominates a distance-based clustering result. What should you have checked before clustering?",
      "choices": [
        "Only the number of rows",
        "The feature scales and distributions",
        "Whether the chart has a title",
        "Only the final cluster labels"
      ],
      "answerIndex": 1,
      "explanation": "The lecture uses an over-spread dimension as an example of why data needs exploration before clustering."
    },
    {
      "id": "L1-003",
      "lecture": 1,
      "concept": "Why explore data",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          11
        ]
      },
      "question": "Why might clustering be inappropriate even if a clustering algorithm runs successfully?",
      "choices": [
        "The data may not contain natural clusters",
        "Clustering only works on images",
        "Any dataset with missing values must be clustered",
        "An algorithm always discovers meaningful groups"
      ],
      "answerIndex": 0,
      "explanation": "An algorithm can always produce labels, but exploration may show there is no meaningful cluster structure."
    },
    {
      "id": "L1-004",
      "lecture": 1,
      "concept": "Why explore data",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          12
        ]
      },
      "question": "Which pair of data issues does Lecture 1 explicitly suggest checking before modelling?",
      "choices": [
        "Font size and slide colour",
        "File name and folder path",
        "Outliers and missing values",
        "Model logo and programming language"
      ],
      "answerIndex": 2,
      "explanation": "The slides explicitly ask whether there are outliers or missing values and how they affect an algorithm."
    },
    {
      "id": "L1-005",
      "lecture": 1,
      "concept": "Why visualise data",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          13
        ]
      },
      "question": "Why is visualisation useful when a dataset becomes large?",
      "choices": [
        "It can reveal patterns that are hard to grasp from raw rows",
        "It always proves causation",
        "It makes data cleaning unnecessary",
        "It can show every high-dimensional relationship perfectly"
      ],
      "answerIndex": 0,
      "explanation": "The slide says large data is difficult to comprehend and visualisation helps us see patterns."
    },
    {
      "id": "L1-006",
      "lecture": 1,
      "concept": "Why visualise data",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          13
        ]
      },
      "question": "What is a reasonable goal of plotting high-dimensional data in fewer dimensions?",
      "choices": [
        "To retain every detail with no loss",
        "To prove that every variable predicts the target",
        "To turn all variables into categories",
        "To make some structure easier to inspect"
      ],
      "answerIndex": 3,
      "explanation": "Lower-dimensional plots help us inspect structure, but they do not preserve all information."
    },
    {
      "id": "L1-007",
      "lecture": 1,
      "concept": "Why explore data",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          10,
          11
        ]
      },
      "question": "Which statement best matches the lecturer's message 'Know it before you machine learn it'?",
      "choices": [
        "Understand the dataset and its limitations before choosing a model",
        "Choose the most advanced model first, then inspect the data",
        "Skip cleaning if the dataset has many rows",
        "A model can always compensate for incorrect input data"
      ],
      "answerIndex": 0,
      "explanation": "The lecturer stresses data cleaning and exploration before modelling."
    },
    {
      "id": "L1-008",
      "lecture": 1,
      "concept": "Why visualise data",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          13
        ]
      },
      "question": "Which of these is NOT something a visualisation alone can establish?",
      "choices": [
        "That a distribution looks skewed",
        "That one variable causes another",
        "That an observation appears unusual",
        "That two variables seem associated"
      ],
      "answerIndex": 1,
      "explanation": "Plots can suggest patterns and unusual values, but an observed association alone does not establish causation."
    },
    {
      "id": "L1-009",
      "lecture": 1,
      "concept": "Real-world data",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          18,
          20
        ]
      },
      "question": "A random forest gives a record ID a high feature-importance score. What should you conclude?",
      "choices": [
        "The ID must cause the target outcome",
        "The model cannot use numerical IDs",
        "Investigate whether the ID reflects a real pattern or a recording artefact",
        "All other features should be deleted"
      ],
      "answerIndex": 2,
      "explanation": "Feature importance shows the model used the column; it does not prove the column carries meaningful or causal information."
    },
    {
      "id": "L1-010",
      "lecture": 1,
      "concept": "Real-world data",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          18
        ]
      },
      "question": "In the displayed table, impact_num increases 0, 1, 2, and so on. What is the sensible first check before treating it as a predictive feature?",
      "choices": [
        "Whether it is only a row number or ordering artefact",
        "Whether its font is readable",
        "Whether it has the same name as the target",
        "Whether it can be plotted as a pie chart"
      ],
      "answerIndex": 0,
      "explanation": "Sequential values may encode row order rather than a property of the event. Investigate what the column means before using it."
    },
    {
      "id": "L1-011",
      "lecture": 1,
      "concept": "Real-world data",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          21
        ]
      },
      "question": "What does the complex database diagram illustrate about real-world data?",
      "choices": [
        "Every dataset is already one clean modelling table",
        "Databases cannot contain numerical measurements",
        "Only one table can be explored at a time",
        "Useful information may be spread across many related tables"
      ],
      "answerIndex": 3,
      "explanation": "Real data may need careful understanding and joins before it becomes a usable analysis table."
    },
    {
      "id": "L1-012",
      "lecture": 1,
      "concept": "Real-world data",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          18,
          19
        ]
      },
      "question": "The decision trees split on a column. Does that alone prove the column is a trustworthy real-world predictor?",
      "choices": [
        "Yes, because trees cannot split on irrelevant data",
        "No, the split may exploit an accidental pattern in the sample",
        "Yes, if the column contains integers",
        "No, because decision trees never use numerical columns"
      ],
      "answerIndex": 1,
      "explanation": "A tree can fit patterns in the sample, including identifiers or artefacts. The feature's meaning and generalisation still need checking."
    },
    {
      "id": "L1-013",
      "lecture": 1,
      "concept": "Real-world data",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          14,
          18
        ]
      },
      "question": "Why does the lecturer contrast familiar example datasets with real-life datasets?",
      "choices": [
        "To show that real datasets often need more understanding and cleaning",
        "To show that example datasets have no value",
        "To prove every real dataset has missing values",
        "To say models cannot be used outside competitions"
      ],
      "answerIndex": 0,
      "explanation": "The contrast motivates exploration: real data is often less tidy and more complex than a teaching or competition example."
    },
    {
      "id": "L1-014",
      "lecture": 1,
      "concept": "Real-world data",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          18
        ]
      },
      "question": "Which column in the displayed table is clearly categorical rather than a numeric measurement or timestamp?",
      "choices": [
        "gps_lat",
        "alert_timestamp",
        "impact_id",
        "cause"
      ],
      "answerIndex": 3,
      "explanation": "The cause column contains labels such as Potholes, Speedbump and Car Wash."
    },
    {
      "id": "L1-015",
      "lecture": 1,
      "concept": "Curse of dimensionality",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          22
        ]
      },
      "question": "In the curse of dimensionality, what does a dimension usually mean?",
      "choices": [
        "A record",
        "A feature",
        "A missing value",
        "A class label"
      ],
      "answerIndex": 1,
      "explanation": "A dimension is an attribute or feature used to represent an observation."
    },
    {
      "id": "L1-016",
      "lecture": 1,
      "concept": "Curse of dimensionality",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          22
        ]
      },
      "question": "Which problem does Lecture 1 explicitly associate with thousands of dimensions?",
      "choices": [
        "Every feature becomes categorical",
        "All data is automatically missing",
        "Visualisation becomes difficult",
        "The dataset cannot be stored"
      ],
      "answerIndex": 2,
      "explanation": "The slide says high-dimensional data is difficult to visualise."
    },
    {
      "id": "L1-017",
      "lecture": 1,
      "concept": "Curse of dimensionality",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          22
        ]
      },
      "question": "What modelling risk does the Lecture 1 slide connect to many dimensions?",
      "choices": [
        "Overfitting",
        "Guaranteed underfitting",
        "Loss of all labels",
        "A fixed number of clusters"
      ],
      "answerIndex": 0,
      "explanation": "With many features, a model can more easily fit peculiarities of the training data rather than a pattern that generalises."
    },
    {
      "id": "L1-018",
      "lecture": 1,
      "concept": "Curse of dimensionality",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          22
        ]
      },
      "question": "Why does the lecturer mention dimensionality reduction?",
      "choices": [
        "To remove every outlier",
        "To prove causation",
        "To convert all numbers into text",
        "To make high-dimensional data easier to visualise"
      ],
      "answerIndex": 3,
      "explanation": "The slide introduces dimensionality reduction as a way to make visualisation easier; its methods come later."
    },
    {
      "id": "L1-019",
      "lecture": 1,
      "concept": "Curse of dimensionality",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          22
        ]
      },
      "question": "Which claim about adding features is safest?",
      "choices": [
        "More features always improve a model",
        "More features can make overfitting easier",
        "Feature count never affects visualisation",
        "A model cannot use more than three features"
      ],
      "answerIndex": 1,
      "explanation": "Lecture 1 warns that many dimensions can make overfitting easier, so more features are not automatically better."
    },
    {
      "id": "L1-020",
      "lecture": 1,
      "concept": "Curse of dimensionality",
      "source": {
        "file": "IDVE_Lecture_1_2026.pdf",
        "pages": [
          22
        ]
      },
      "question": "Does a lower-dimensional visualisation necessarily preserve every detail of the original high-dimensional data?",
      "choices": [
        "Yes, always",
        "Only if the data has no outliers",
        "No, reducing dimensions can leave information out",
        "Only if the data has labels"
      ],
      "answerIndex": 2,
      "explanation": "The purpose is to make inspection easier, but reducing dimensions can discard or hide some information."
    }
  ]
};
